### ISSUE TITLE
Channel Group Changer Script

### ISSUE THREAD

**Issue by itseyup** [Bluscream/pyTSon_plugins#104]
Hi, I use pyTSon Channel Group Changer script a lot. But when I want to right click on my client and change my channel group, I cannot enter any number more than "99". How can I change this? I'm not much of a python person. Thanks!

**Comment by Bluscream** [comment]
This should hopefully be enough: https://github.com/Bluscream/pyTSon_plugins/commit/e48a0b7e9186b9f142c9247d1077d6c2567985a5#diff-d8c0d8eb9ec81b98f6c48ed122f8823e612817c809e5bf1d6d6bb80f16f4cac5R120

Lemme know if it works

**Comment by itseyup** [comment]
It works fine, thanks!
