### ISSUE TITLE
nickRotate

### ISSUE THREAD

**Issue by EtexKG** [Bluscream/pyTSon_plugins#13]
Installed everything with pyTSon, but it doesn't show on pyTSon Settings Page.. 

https://image.prntscr.com/image/mdC2Ht04Ti2qitRd3QSA8Q.png

Or if you could record the whole installation process or write it down, please. Thank you! :+1:  :)

**Comment by Bluscream** [comment]
Check your client log ([CTRL]+[L])

**Comment by EtexKG** [comment]
https://image.prntscr.com/image/AkPFsi2-R4O21VSeOyUnQQ.png

**Comment by Bluscream** [comment]
ehhm please report that error to https://github.com/pathmann/pyTSon/issues/new

**Comment by EtexKG** [comment]
Could you please record or write the whole install process of this pyTSon script? Thank you very much!

**Comment by Bluscream** [comment]
There's a german tutorial available at https://r4p3.net/resources/pytson.170/field?field=faq

**Comment by EtexKG** [comment]
Should be helpful. But my TeamSpeak crashes when I install pyTSon automatically. If I do it manually it's allright, but I can't run it with auto installed pyTSon

**Comment by EtexKG** [comment]
Oh, I did follow the tutorial, and I managed to install the script, but how can I activate? I mark it on Settings page of pyTSon, but what's the next step?

**Comment by Bluscream** [comment]
strange, but that's another issue you should report to pathmann/pyTSon

**Comment by Bluscream** [comment]
This issue has been closed because of inactivity, if you think this happened by accident re-open it.
