### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by kisbalazspatrik** [Bluscream/pyTSon_plugins#17]
First error:
https://imgur.com/a/P77x3
and this is an infinite loop.

**Comment by Bluscream** [comment]
What did you try to install?

**Comment by kisbalazspatrik** [comment]
https://github.com/Bluscream/pyTSon_plugins/releases/download/CustomBadges/CustomBadges.ts3_plugin

**Comment by robotrono** [comment]
@Bluscream hmm I add the script in AppData\Roaming\TS3Client\plugins\pyTSon\scripts\customBadges but in PyTSon settings cant see the plugin

I have installed TS3 Hook and pyTSon plugins. 

https://i.imgur.com/h1TlEjE.png

https://i.imgur.com/VZ2U6s0.png

https://i.imgur.com/QUwEVM7.png

**Comment by robotrono** [comment]
Then I installed this plugin:

https://github.com/Bluscream/pyTSon_plugins/releases/download/CustomBadges/CustomBadges.ts3_plugin

Works, but I cant see the badges https://i.imgur.com/G8dfnJO.png

**Comment by Bluscream** [comment]
Ask others if they can see them

**Comment by robotrono** [comment]
@Bluscream works now, I reinstall TS3Hook and works fine. btw I can get a ban to myteamspeak account for this?

**Comment by Bluscream** [comment]
No, myTeamspeak doesn't actually know what badges you are using with the plugin and they don't have a ban system in place as of now. if they do something like that i will shut down the plugin globally to minimize risks
