### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by dzinks2009** [Bluscream/pyTSon_plugins#19]
Hello, when I launch customBadges, my TeamSpeak3 crashes.

https://prnt.sc/jgqar4

Loading plugin: pyTSon_win64.dll
Failed to load plugin: **/AppData\Roaming\TS3Client\plugins\pyTSon_win64.dll

2018-05-11 20:45:55.422262|INFO    |Plugins       |   |LoadLibrary error: 126

**Comment by Bluscream** [comment]
Try to install the 3 parts one by one: https://r4p3.net/threads/custom-badges-aio.6000/page-2#post-52746
