### ISSUE TITLE
Change Ping

### ISSUE THREAD

**Issue by GitSimonHub** [Bluscream/pyTSon_plugins#23]
Hey Bluescream,
you answered my question to change my ping with this link https://github.com/Bluscream/pyTSon_plugins/blob/master/scripts/crasher_3_1_7/__init__.py#L89

but i dont know, how to use this.
What do i need to to?

**Comment by Bluscream** [comment]
Just like any other script in the repo https://github.com/Bluscream/pyTSon_plugins#short-tutorial
