### ISSUE TITLE
Set Badges on TS start

### ISSUE THREAD

**Issue by GitSimonHub** [Bluscream/pyTSon_plugins#25]
Hey i'd like to automatic set "~cmdclientupdate~sclient_badges=overwolf=0:badges=450f81c1-ab41-4211-a338-222fa94ed157,c9e97536-5a2d-4c8e-a135-af404587a472,94ec66de-5940-4e38-b002-970df0cf6c94"
if i start TS, this is to set "fake" badges.
How can i do this if its possible

**Comment by exp111** [comment]
There is a settings.ini (scripts/customBadges/settings.ini) where you can change the badges (line 4; separated by commas).
