### ISSUE TITLE
Ping changer dont work

### ISSUE THREAD

**Issue by GitSimonHub** [Bluscream/pyTSon_plugins#26]
Hey
i've set up the "TS3 3.1.7 crasher" to change my ping, but it doesn't work?
In the Console there is [OUT] and something with ping and 1337.
But i asked my friend whats my ping is, and he said my real ping

**Comment by Bluscream** [comment]
come to playshot.de

**Comment by Bluscream** [comment]
kein ding, wenn was is ich bin da ^^

**Comment by GitSimonHub** [comment]
An sich klappt es ja, aber der Ping ändert sich ständig von meinem richtigen zum gefaketen 1337ner ping.
Ist das "normal" oder kann man das fixen?

**Comment by Bluscream** [comment]
was meinst du?

**Comment by exp111** [comment]
Das sollte passieren da wir nicht connectioninfoupdate blocken (in dem crasher_3.1.7) und somit ts3 noch selber ping updates schickt aber das plugin auch
