### ISSUE TITLE
Wofür sind diese Scripts?

### ISSUE THREAD

**Issue by GitSimonHub** [Bluscream/pyTSon_plugins#30]
Hey, in dem master sind ja schon einige scripts, aber ich verstehe teilweise nicht wirklich wofür die sind.
Da es auch nirgendwo steht (ausser in dem namen).
Ich sehe einfach nichts wenn ich einige scripts aktiviere. Oder ich verstehe nicht wie man diese benutzt
z.B:
NoX BanBypasser
troll
faker
fakeClient

**Comment by Bluscream** [comment]
NoX ist noch nicht funktionstüchtig.
troll ist jetzt quickPermissions aka quickPerms und gibt dir clientrechte wann immer du ne servergruppe kriegst.
faker funzt noch nich weil utf-8 in python spackt (https://github.com/pathmann/pyTSon/issues/93)
fakeclients nutzt ts3hook um fake clients auf den server connecten zu lassen

**Comment by GitSimonHub** [comment]
und diese fakeClient, die sehen dann auch andere oder?
Und wie funktioniert das script?

**Comment by Bluscream** [comment]
Nein die sieht man nur selbst

`/py fc <anzahl>`
