### ISSUE TITLE
BanBypasser (NoX)

### ISSUE THREAD

**Issue by Disgame** [Bluscream/pyTSon_plugins#31]
Hey, warum kann ich in Pytson BanBypasser (NoX) nicht aktivieren? Ich bekomme ständig die Meldung "Fehler beim Starten des Plugins, mehr Informationen im Client Protokoll" . Kannst du mir da weiterhelfen ?

**Comment by GitSimonHub** [comment]
Bluescream hat mir geantwortet dass der noch nicht funktioniert.

**Comment by GitSimonHub** [comment]
Schau mal bei issues bei "Wofür sind diese Scripts?"

**Comment by Disgame** [comment]
Ah ok, danke :D

**Comment by Bluscream** [comment]
Already answered in #30
