### ISSUE TITLE
Wie funktioniert fakeClients?

### ISSUE THREAD

**Issue by GitSimonHub** [Bluscream/pyTSon_plugins#32]
Der titel sagt alles oder?

**Comment by Bluscream** [comment]
Guck dir den code an

**Comment by GitSimonHub** [comment]
ich verstehe den code halt nicht ;|
Wenn ich auf eine andere Person im TS rechtsklick mache, und unter pythson dann z.B. kick kliche schreibe ich mir nur: "-cmdnotifyclientleftview~scfid=2833713~sctid=0~sreasonid=5~sreasonmsg=kicked~sclid=719~sinvokerid=0~sinvokername=Server~sinvokeruid"

**Comment by Bluscream** [comment]
Du brauchst TS3Hook

**Comment by GitSimonHub** [comment]
Habe ich :D
Dinge wie das Custom Badges funktionieren.

**Comment by GitSimonHub** [comment]
ich schaue mal. Ich installieren den Hook mal neu

**Comment by GitSimonHub** [comment]
Ah okay, jetzt klappt es.
Aber dann ist der Client nur für mich weg bzw. nur ich höre den sound oder?

**Comment by Bluscream** [comment]
ja
