### ISSUE TITLE
BanBypasser (NoX)

### ISSUE THREAD

**Issue by Disgame** [Bluscream/pyTSon_plugins#33]
Was ist fehlt eigentlich an dem Script noch, dass es funktioniert? Währe nämlich echt nice wenn es funktionieren würde

**Comment by Disgame** [comment]
Und wer kam auf die Idee bei z.B. "Change Identidy" einen Troll Sound mit rein zu bringen? xD

**Comment by Bluscream** [comment]
Das aktuelle nox script ist nicht von mir sondern https://github.com/exp111/pyTSon-Scripts/tree/master/NoX
