### ISSUE TITLE
Badges won't load

### ISSUE THREAD

**Issue by iLukeOff** [Bluscream/pyTSon_plugins#36]
` ~cmdclientupdate~sclient_badges=overwolf=0:badges=935e5a2a-954a-44ca-aa7a-55c79285b601,c3f823eb-5d5c-40f9-9dbd-3437d59a539d,64221fd1-706c-4bb2-ba55-996c39effa79:badges=xd52ttaw-7uuq-tyex-plnw-7dg6ykp856dq,0c4u2snt-ao1m-7b5a-d0gq-e3s3shceript,50bbdbc8-0f2a-46eb-9808-602225b49627`

**Comment by Bluscream** [comment]
I know the command to set badges, you don't have to send me that.

**Comment by iLukeOff** [comment]
that's the output i get when i try to put in the command 
![bildschirmfoto 2018-06-14 um 11 26 25](https://user-images.githubusercontent.com/36594215/41403789-07f9e1ac-6fc6-11e8-9890-444f7a1a4cad.png)

**Comment by iLukeOff** [comment]
@exp111 so for me it isn't possible anyway because i use mac or what?

**Comment by Bluscream** [comment]
@iLukeOff yes

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ARYX01** [comment]
External badges are not visible to other users?

**Comment by Bluscream** [comment]
@ARYX01 yes, they are not

**Comment by iLukeOff** [comment]
@Bluscream isn't there a way to set badges to with a command

**Comment by Bluscream** [comment]
@iLukeOff Yes, but the script is there so you don't have to set them with a command.
