### ISSUE TITLE
hello can you help me

### ISSUE THREAD

**Issue by ImScopy** [Bluscream/pyTSon_plugins#39]
i was want a thing that if some one join specific channel it move to another specific channel (automatically)
if i online 

or i have a scirpt for lua that u can type /lua run move (to) (from)
but i must enter the command manuly i any way to make the command send automatically ?

**Comment by Bluscream** [comment]
What?

**Comment by ImScopy** [comment]
you dont understand i wrote ?

**Comment by Bluscream** [comment]
Not at all

**Comment by Bluscream** [comment]
Whats your native language?

**Comment by ImScopy** [comment]
i want script who move any body join a channel to another channel i choose

**Comment by Bluscream** [comment]
Where are you from?

**Comment by Bluscream** [comment]
Not if i can't understand what you want because you are unable to learn proper english. Closed
