### ISSUE TITLE
you should under stand me now

### ISSUE THREAD

**Issue by AhmeedMostafa** [Bluscream/pyTSon_plugins#40]
http://prntscr.com/kbv2xc

you see the red arrow ?
then this is the room i want if user join the channel 
move him automatically to the green arow channel

basically it automove plugin
simply i want any body join (waiting for activation )
move to activation room 1 
under stand me now
icant get bot because the server isnt mine and i am activatior in it who activate new people 
so i want plugin who help me move people fast to the activation room 1

**Comment by ImScopy** [comment]
so what is the languge i should learn ? 

it is easy for you to make it
but me it is so hard for me it may take from me like 4 days
but you only 10 min

**Comment by Bluscream** [comment]
Python. Make sure the stuff u learn is for python 3

**Comment by Bluscream** [comment]
Also after 4 days the next one will also be 10 minutes for you

**Comment by ImScopy** [comment]
any website easy for learning ?

from ur advice

**Comment by Bluscream** [comment]
search for python 3 tutorial

**Comment by Bluscream** [comment]
Also look at my plugins to learn

**Comment by ImScopy** [comment]
any plugin from yours is similar to what i need ?
