### ISSUE TITLE
Last time 

### ISSUE THREAD

**Issue by ImScopy** [Bluscream/pyTSon_plugins#41]
i try out to make a script and i fail
if you please please do it for me
i will do anything for you it so important to me
i can do a shoutout on my yt channel 500 sub :(
or pay money i just need on client join channel move him to another channel automatically that it
please dont ignore me i need your help be helpful and i swear i will do tutorials on your scripts

**Comment by Bluscream** [comment]
You should ask for it on https://r4p3.net

**Comment by exp111** [comment]
[Here](https://github.com/exp111/pyTSon-Scripts/tree/master/autoMove)
