### ISSUE TITLE
Same Issue as last time

### ISSUE THREAD

**Issue by Disgame** [Bluscream/pyTSon_plugins#43]
Can't see all Plugins :) In "Include" might be some bugs

**Comment by Bluscream** [comment]
Client log?

**Comment by Disgame** [comment]
01.08.2018 12:11:04	pyTSon.PluginHost.invokePlugins	Info	Fehler beim Aufruf von currentServerConnectionChanged im Plugin BanBypasser (NoX): Traceback (most recent call last):
###   **File "C:/Users/enric_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 394, in invokePlugins
    ret.append(meth(*args))**
  File "C:/Users/enric_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\NoX\__init__.py", line 190, in currentServerConnectionChanged
    ts3lib.printMessageToCurrentTab("{0}Server changed to {1}. The ClientID is now {2}".format(timestamp(), clientID))
IndexError: tuple index out of range

**Comment by Disgame** [comment]
01.08.2018 12:11:04	pyTSon.PluginHost.invokePlugins	Info	Fehler beim Aufruf von currentServerConnectionChanged im Plugin BanBypasser (NoX): Traceback (most recent call last):
  ### File "C:/Users/random/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 394, in invokePlugins
    ret.append(meth(*args))
  File "C:/Users/Random/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\NoX\__init__.py", line 190, in currentServerConnectionChanged
    ts3lib.printMessageToCurrentTab("{0}Server changed to {1}. The ClientID is now {2}".format(timestamp(), clientID))
IndexError: tuple index out of range

**Comment by Bluscream** [comment]
bekannter bugm wird gefixxt
