### ISSUE TITLE
PasswordCracker not displayed in Plugins List

### ISSUE THREAD

**Issue by Darkodoudou** [Bluscream/pyTSon_plugins#45]
Hey! I have an **issue** with **this plugin** (**https://github.com/Bluscream/pyTSon_plugins/tree/master/scripts/passwordCracker**), **I followed the steps** and **I do not have it displayed** in the list. 

**Logs:** https://pastebin.com/VjK5VQV6

psutil is installed (via pip) with the *.whl file (https://pypi.org/project/psutil/#files)

Sorry if the problem is already solved but I didn't find any answer in the posted issues, thank you.

**Comment by Bluscream** [comment]
Same issue as #43, closed
