### ISSUE TITLE
Anfrage 

### ISSUE THREAD

**Issue by ameyst** [Bluscream/pyTSon_plugins#46]
kannst du das autocommander erweitern das wenn man spricht der cannelcommander eingeschaltet wird und wenn man fertig ist wieder aus?

**Comment by Bluscream** [comment]
Klar :)

**Comment by ameyst** [comment]
nice :+1:

**Comment by Bluscream** [comment]
Ist fertig :man_cook:

**Comment by ameyst** [comment]
ist ein wenig bugy, soll solange gelb sein bis man aufhöhrt zu sprechen? und erstwieder angehen wenn man spricht? bei fragt er mich nach einer zeit in ms wenn man nicht 0 eingibt kommt ok gespammt und bei 0 blingt es nur kommisch was mache ich falsch?

**Comment by Bluscream** [comment]
Ups hab den knopf nicht entfernt, ist jz nachgeholt aber wenn du den kopf mit angeschaltetem channel commander drückst (also der der leuchtet gehts auch in deiner version schon)

**Comment by Bluscream** [comment]
Zufrieden?

**Comment by ameyst** [comment]
hast du ne ts3 server adresse?
plugin läd nicht mehr

**Comment by Bluscream** [comment]
Ja hab ich

**Comment by ameyst** [comment]
können wir fix mal quatschen?

**Comment by Bluscream** [comment]
Können wir, ja

**Comment by ameyst** [comment]
adresse?

**Comment by Bluscream** [comment]
ts.minopia.de:9989

**Comment by ameyst** [comment]
ok geht ohne passwort leider nicht

**Comment by ameyst** [comment]
￼<22:55:25> Ungültiges Server Passwort.

**Comment by Bluscream** [comment]
pw = sarah

**Comment by Bluscream** [comment]
Wurde geklärt.
