### ISSUE TITLE
Badges error

### ISSUE THREAD

**Issue by mrfrancuz07** [Bluscream/pyTSon_plugins#47]
![image](https://user-images.githubusercontent.com/15146321/44520884-93a15680-a6d1-11e8-99ff-3ab698ab0369.png)
Using TS3Hook v1.2.3 & CustomBadges v0.9.5

**Comment by Bluscream** [comment]
Omg i forgot to replace the \s's. Thanks will fix that asap

**Comment by Bluscream** [comment]
Can you test https://github.com/Bluscream/pyTSon_plugins/releases/tag/CustomBadges @mrfrancuz07 ?

**Comment by mrfrancuz07** [comment]
Works.

**Comment by Bluscream** [comment]
Nice, thanks for testing :)
