### ISSUE TITLE
[Question]How to activate the "external" badges?

### ISSUE THREAD

**Issue by SkyCZ** [Bluscream/pyTSon_plugins#48]
Any ideas doble-click doesnt work

**Comment by exp111** [comment]
No idea how to enable it, but it's currently useless as nobody will see the badges. We're currently trying to fix that.

**Comment by SkyCZ** [comment]
Ok thank you tell me when it will be fixed please :)

**Comment by Bluscream** [comment]
Something that was never working can't be "fixed" it can just be implemented.

**Comment by exp111** [comment]
Install [this](https://github.com/exp111/pyTSon-Scripts/tree/master/scripts/serverTreeViewDelegate) if you want to see external & faked badges
