### ISSUE TITLE
Can't use functions of PyTSon

### ISSUE THREAD

**Issue by Dejvis96** [Bluscream/pyTSon_plugins#50]
I have (I think) such casual question-problem, since I am pretty new to this addon.
Why all of those scripts are grayed out?
![seyf](https://user-images.githubusercontent.com/24878593/49611303-67b89100-f9a1-11e8-8af7-b0ce695ff816.png)

**Comment by Bluscream** [comment]
https://github.com/pathmann/pyTSon/issues/110#issuecomment-445029851

**Comment by Dejvis96** [comment]
Sure I did.
